  - name: Basic tools
    apt: 
      name: ['rsync', 'dnsutils', 'vim', 'unattended-upgrades', 'sudo']
      update_cache: true
      state: present 

  - name: Setup unattended-upgrades (part 1)
    copy:
      content: ""
      dest: /etc/apt/apt.conf.d/20auto-upgrades 
      force: no
      group: root
      owner: root
      mode: 0644

  - name: Setup unattended-upgrades (part 2)
    lineinfile:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: 'APT::Periodic::Update-Package-Lists', line: 'APT::Periodic::Update-Package-Lists "1";' }
      - { regexp: 'APT::Periodic::Unattended-Upgrade', line: 'APT::Periodic::Unattended-Upgrade "1";' }

  - name: Setup vim (part 1) 
    alternatives:
      name: editor
      path: /usr/bin/vim.basic

  - name: Setup vim (part 2)
    copy:
      content: ""
      dest: /root/.vimrc
      force: no
      group: root
      owner: root
      mode: 0600

  - name: Setup vim (part 3)
    lineinfile:
      dest: /root/.vimrc
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^syntax', line: 'syntax on' }
      - { regexp: '^set showmatch', line: 'set showmatch' }
      - { regexp: '^set number', line: 'set number' }
      - { regexp: '^set mouse', line: 'set mouse=""' }

  - name: Disable password based root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin without-password"
                state=present
    notify: Restart ssh 


