  - name: Loading kernel modules (part 1)
    community.general.modprobe:
      name: overlay
      state: present
 
  - name: Loading kernel modules (part 2)
    community.general.modprobe:
      name: br_netfilter
      state: present
 
  - name: Setup kernel modules (part 1)
    copy:
      content: ""
      dest: /etc/modules-load.d/containerd.conf 
      force: no
      group: root
      owner: root
      mode: 0644

  - name: Setup kernel modules (part 2)
    lineinfile:
      dest: /etc/modules-load.d/containerd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: 'overlay', line: 'overlay' }
      - { regexp: 'br_netfilter', line: 'br_netfilter' }

  - name: Install required tools for containerd
    apt: 
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: true
      state: present 

  - name: Install Docker apt key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg 
      state: present

  - name: Add containerd repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
      state: present
      update_cache: true

  - name: Install containerd
    apt: 
      name: containerd.io
#      name: containerd.io=1.4.6-1
      update_cache: true
      state: present 

#  - name: Prevent containerd from being upgraded
#    dpkg_selections:
#      name: containerd
#      selection: hold

  - name: Ensure containerd is initialized
    shell: containerd config default > /etc/containerd/config.toml && touch /etc/containerd/.init_done
    args:
      creates: /etc/containerd/.init_done
    notify: Restart containerd 

  - name: Set containerd options
    lineinfile:
      path: /etc/containerd/config.toml
      insertafter: '^(\s+)\[plugins.+\w\.runc\.options\]'
      line: '            SystemdCgroup = true'

